// Generated by CoffeeScript 1.10.0
module.exports = {
  plural: function(n, singular, plural, fn) {
    var ns;
    if (fn == null) {
      fn = function(n) {
        return n.toString();
      };
    }
    ns = fn(n);
    if (n === 1) {
      return ns + " " + singular;
    }
    return ns + " " + plural;
  }
};
