// Generated by CoffeeScript 1.10.0
module.exports = {
  plural: function(n, singular, plural, fn) {
    var ns;
    if (fn == null) {
      fn = function(n) {
        return n.toString();
      };
    }
    ns = fn(n);
    if (n === 1) {
      return ns + " " + singular;
    }
    return ns + " " + plural;
  },
  oxford: function(array) {
    var i, index, item, len, result;
    if (array.length <= 1) {
      return array;
    }
    result = [];
    for (index = i = 0, len = array.length; i < len; index = ++i) {
      item = array[index];
      result.push(item);
      if (index < array.length - 2) {
        result.push(', ');
      } else if (index === array.length - 2) {
        result.push(' and ');
      }
    }
    return result;
  }
};
